---
name: evcc (nightly)
version: nightly.20251203-d351253
slug: evcc-nightly
description: Nightly version of EV Charge Controller!
url: https://github.com/evcc-io/evcc
arch: 
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
panel_icon: mdi:ev-station
panel_admin: false
boot: auto
legacy: true
stage: experimental
ingress: true
ingress_port: 7070
init: false
watchdog: http://[HOST]:[PORT:7070]
image: evcc/evcc
options:
  sqlite_file: /data/evcc.db
schema:
  sqlite_file: str
  config_file: str?
  EVOPT_URI: url?
  SEMP_BASE_URL: url?
host_network: true
homeassistant_api: true
map: 
  - type: addon_config
    read_only: False
  - type: homeassistant_config
    read_only: False
uart: true
webui: http://[HOST]:[PORT:7070]/
ports:
  4712/tcp: 4712
  5200/tcp: 5200
  5201/tcp: 5201
  5353/udp: 5353
  7050/tcp: 7050
  7090/udp: 7090
  8887/tcp: 8887
  8888/tcp: 8888
  8899/udp: 8899
  9522/udp: 9522
ports_description:
  4712/tcp: "EEBUS"
  5200/tcp: "Modbus Proxy"
  5201/tcp: "Modbus Proxy (multi port)"
  5353/udp: "Multicast DNS (mDNS)"
  7050/tcp: "evopt API"
  7090/udp: "Keba"
  8887/tcp: "OCPP web socket"
  8888/tcp: "Simple Energy Management Protocol"
  8899/udp: "Modbus UDP"
  9522/udp: "SMA Speedwire Multicast"
